# Generated by Django 3.0.5 on 2020-10-10 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='instagram_handle',
            new_name='social_media',
        ),
    ]
